# Generated by Django 4.2.11 on 2024-04-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olle', '0002_remove_user_email_constraint_remove_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='x_value',
            new_name='first_number',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='y_value',
            new_name='second_number',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='answer',
            new_name='user_answer',
        ),
        migrations.AlterField(
            model_name='task',
            name='user_answer',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='visual_help',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_email',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='operator',
            field=models.CharField(max_length=1),
        ),
    ]
