# Generated by Django 4.2.11 on 2024-04-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olle', '0003_rename_x_value_task_first_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagementAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('access_code', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSynchronization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olle.usermanagementaccount')),
                ('users', models.ManyToManyField(to='olle.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usermanagementaccount',
            constraint=models.UniqueConstraint(fields=('email',), name='email_constraint'),
        ),
        migrations.AddConstraint(
            model_name='usersynchronization',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='per_account_name_constraint'),
        ),
    ]
