version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn django_backend.wsgi:application --bind 0.0.0.0:8088 --log-level debug --capture-output --timeout 60
    ports:
      - 8088:8088
    restart: always
    env_file:
      - ./.env.web
    depends_on:
      - db
    volumes:
      - .:/home/app/web

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
