name: Dart

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter --version
      
      - name: Install dependencies
        working-directory: ./frontend
        run: dart pub get

      - name: Format code (non-blocking)
        working-directory: ./frontend
        run: |
          dart format .
          echo "⚠️ Código foi formatado automaticamente, mas o build continuará normalmente."

      # Atualmente ignorando flutter-cpp-plugin
      - name: Analyze project source
        working-directory: ./frontend
        run: dart analyze #--fatal-infos
